### ISSUE TITLE
Use google tensorstore to read/write to zarr?

### ISSUE THREAD

**Issue by TomNicholas** [cubed-dev/cubed#187]
I expect you're already aware of this @tomwhite , but I wanted to ask whether or not you thought the [google-tensorstore project](https://ai.googleblog.com/2022/09/tensorstore-for-high-performance.html) might be useful in cubed. @rabernat [suggested](https://discourse.pangeo.io/t/google-tensorstore-3d-data-package/2778) benchmarking its performance against zarr-python + fsspec. Presumably any improvement to the I/O speed would considerably increase the performance of cubed? Stephan recently released an [xarray interface to tensorstore](https://github.com/google/xarray-tensorstore) but it seems like that's not the right entry point for using it with cubed.

**Comment by tomwhite** [comment]
Yes, I saw this and think it could be very interesting for Cubed.

> Presumably any improvement to the I/O speed would considerably increase the performance of cubed?

Hopefully, but we'd have to try it out to see.

**Comment by tomwhite** [comment]
I tried swapping out Zarr for TensorStore here: https://github.com/tomwhite/cubed/tree/tensorstore. All unit test pass, except for `test_resume` (since TensorStore doesn't have a way of accessing Zarr's `nchunks_initialized`).

There were a few challenges due to differences in handling structured arrays, which we use for reductions like `mean`, but it looks like things would work. We probably will want a way to specify the array storage in the spec so users can select the one they want.

I haven't done any performance testing, but the current branch is sufficiently developed to try that.
